# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WheelPath' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WheelPath

pod 'Firebase/Core'

pod 'Firebase/Database'

pod 'Firebase/Auth'

pod 'Firebase/Storage'

pod 'MKPolygon-GPC', '~> 0.0.1'

  target 'WheelPathTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WheelPathUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
